---
  - name: Update apt repository
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install default packages
    apt: name={{ packages.default }} state=present
    when: programs_packages_default | bool

  - name: Install development packages
    apt: name={{ packages.development }} state=present
    when: programs_packages_development | bool

  - name: Install server packages
    apt: name={{ packages.server }} state=present
    when: programs_packages_server | bool

  - name: Install Snap packages
    snap: 
      name: discord
      channel: latest/stable
    # with_items: "{{ packages.snap }}"
