---
- name: Copy bash_alias file
  copy:
    src: files/.bash_aliases
    # TODO : var on username
    dest: /home/alex/.bash_aliases
    # TODO change to alex / var username
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes

