---
- name: Creating man directory need for jdk install
  file:
   group: "root"
   mode: '751'
   owner: "root"
   path: "/usr/share/man/man1"
   state: "directory"

- name: Install jdk 8 & 11
  apt: name={{item}} state=latest update_cache=yes
  loop: ['openjdk-8-jdk', 'openjdk-11-jdk']

- name: Setup java_home with alternatives (default 8)
  alternatives:
   name: "java"
   path: "{{ item.path }}"
  with_items: 
    - { version: "8", path: "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" }
    - { version: "11", path: "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"}
  when: item.version == java_version

- name: Install maven
  apt: name=maven state=latest update_cache=yes
